import { type Product } from '@ecom/types';

/** Demo catalog data: replace with a real API call via createApiClient. */

function unsplash(photoId: string, width = 800): string {
  return `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=${width}&q=80`;
}

export const DEMO_PRODUCTS: Product[] = [
  // ── Smartphones ────────────────────────────────────────────────────────
  {
    id: 'p-1',
    name: 'Galaxy S22 Ultra',
    description:
      'The Galaxy S22 Ultra combines the power of the Note series with the camera intelligence of the S line. Its 108MP sensor with Nightography captures stunning detail in near darkness, the embedded S Pen turns the 6.8" QHD+ display into a canvas, and the 5000mAh battery keeps up with your longest days.',
    price: 65999,
    mrp: 74999,
    currency: 'INR',
    category: 'Smartphones',
    rating: 4.7,
    inStock: true,
    imageUrl: unsplash('photo-1610945265064-0e34e5519bbf'),
    images: [
      unsplash('photo-1610945265064-0e34e5519bbf', 1200),
      unsplash('photo-1601784551446-20c9e07cdbdb', 1200),
      unsplash('photo-1580910051074-3eb694886505', 1200),
    ],
    highlights: [
      '108MP wide camera with Nightography and 100x Space Zoom',
      'Embedded S Pen with 2.8ms latency for notes and sketches',
      '6.8" Dynamic AMOLED 2X, QHD+ at adaptive 120Hz',
      '5000mAh battery with 45W super fast charging',
      'Armor Aluminum frame with Gorilla Glass Victus+',
    ],
    specs: {
      Display: '6.8" QHD+ Dynamic AMOLED 2X, 120Hz',
      Processor: 'Snapdragon 8 Gen 1 (4nm)',
      Memory: '12GB RAM | 256GB storage',
      'Rear camera': '108MP + 12MP + 10MP + 10MP',
      'Front camera': '40MP',
      Battery: '5000mAh, 45W wired / 15W wireless',
      Colour: 'Burgundy',
      Warranty: '1 year manufacturer warranty',
    },
  },
  {
    id: 'p-2',
    name: 'Galaxy M13 (4GB | 64 GB)',
    description:
      'Built for marathon days, the Galaxy M13 packs a massive 6000mAh battery behind a bright 6.6" FHD+ display. The 50MP triple camera handles everyday shots with ease, and expandable storage up to 1TB means you never have to choose what to keep.',
    price: 10499,
    mrp: 14999,
    currency: 'INR',
    category: 'Smartphones',
    rating: 4.3,
    inStock: true,
    imageUrl: unsplash('photo-1598327105666-5b89351aff97'),
    images: [
      unsplash('photo-1598327105666-5b89351aff97', 1200),
      unsplash('photo-1565849904461-04a58ad377e0', 1200),
      unsplash('photo-1533228100845-08145b01de14', 1200),
    ],
    highlights: [
      '6000mAh battery with 15W fast charging',
      '50MP triple rear camera with depth and macro lenses',
      '6.6" FHD+ Infinity-V display',
      'Expandable storage up to 1TB via microSD',
    ],
    specs: {
      Display: '6.6" FHD+ PLS LCD',
      Processor: 'Exynos 850 (8nm)',
      Memory: '4GB RAM | 64GB storage, expandable to 1TB',
      'Rear camera': '50MP + 5MP + 2MP',
      'Front camera': '8MP',
      Battery: '6000mAh, 15W fast charging',
      Warranty: '1 year manufacturer warranty',
    },
  },
  {
    id: 'p-3',
    name: 'Galaxy M33 (4GB | 64 GB)',
    description:
      'The Galaxy M33 5G is ready for tomorrow’s networks today. A smooth 120Hz display keeps scrolling fluid, the 5nm processor handles gaming without breaking a sweat, and the 6000mAh battery goes well past a full day.',
    price: 16999,
    mrp: 24999,
    currency: 'INR',
    category: 'Smartphones',
    rating: 4.4,
    inStock: true,
    imageUrl: unsplash('photo-1511707171634-5f897ff02aa9'),
    images: [
      unsplash('photo-1511707171634-5f897ff02aa9', 1200),
      unsplash('photo-1523206489230-c012c64b2b48', 1200),
      unsplash('photo-1567581935884-3349723552ca', 1200),
    ],
    highlights: [
      '5G ready with 12 bands supported',
      '6.6" FHD+ display with 120Hz refresh rate',
      '50MP quad camera setup',
      '6000mAh battery with 25W fast charging',
    ],
    specs: {
      Display: '6.6" FHD+ TFT, 120Hz',
      Processor: 'Exynos 1280 (5nm)',
      Memory: '4GB RAM | 64GB storage',
      'Rear camera': '50MP + 5MP + 2MP + 2MP',
      'Front camera': '8MP',
      Battery: '6000mAh, 25W fast charging',
      Warranty: '1 year manufacturer warranty',
    },
  },
  {
    id: 'p-4',
    name: 'Galaxy M53 (4GB | 64 GB)',
    description:
      'Flagship looks without the flagship price. The Galaxy M53 pairs a 108MP camera with a silky Super AMOLED+ 120Hz display in a slim 7.4mm body, so your photos and your feed both look their best.',
    price: 31999,
    mrp: 40999,
    currency: 'INR',
    category: 'Smartphones',
    rating: 4.5,
    inStock: true,
    imageUrl: unsplash('photo-1592899677977-9c10ca588bbd'),
    images: [
      unsplash('photo-1592899677977-9c10ca588bbd', 1200),
      unsplash('photo-1512941937669-90a1b58e7e9c', 1200),
      unsplash('photo-1580910051074-3eb694886505', 1200),
    ],
    highlights: [
      '108MP main camera with no-shake photos',
      '6.7" Super AMOLED+ display at 120Hz',
      'Slim 7.4mm design at just 176g',
      '5000mAh battery with 25W fast charging',
    ],
    specs: {
      Display: '6.7" FHD+ Super AMOLED+, 120Hz',
      Processor: 'Dimensity 900 (6nm)',
      Memory: '4GB RAM | 64GB storage',
      'Rear camera': '108MP + 8MP + 2MP + 2MP',
      'Front camera': '32MP',
      Battery: '5000mAh, 25W fast charging',
      Warranty: '1 year manufacturer warranty',
    },
  },

  // ── Audio ──────────────────────────────────────────────────────────────
  {
    id: 'p-5',
    name: 'Buds Pro Wireless Earbuds',
    description:
      'Immerse yourself in studio-quality sound. Intelligent active noise cancellation adapts to your surroundings, 360 Audio keeps you at the centre of the mix, and the pocketable case tops you up to 28 hours of total playtime.',
    price: 4999,
    mrp: 7999,
    currency: 'INR',
    category: 'Audio',
    rating: 4.5,
    inStock: true,
    imageUrl: unsplash('photo-1590658268037-6bf12165a8df'),
    images: [
      unsplash('photo-1590658268037-6bf12165a8df', 1200),
      unsplash('photo-1606220945770-b5b6c2c55bf1', 1200),
      unsplash('photo-1572569511254-d8f925fe2cbb', 1200),
      unsplash('photo-1583394838336-acd977736f90', 1200),
    ],
    highlights: [
      'Intelligent active noise cancellation',
      '360 Audio with Dolby head tracking',
      '28-hour total playtime with the charging case',
      'IPX7 water resistance for workouts',
      'Seamless auto-switching between devices',
    ],
    specs: {
      Driver: '11mm woofer + 6.5mm tweeter',
      'Noise cancellation': 'Intelligent ANC with ambient mode',
      Battery: '5h (buds, ANC on) / 28h with case',
      Charging: 'USB-C and Qi wireless',
      'Water resistance': 'IPX7',
      Connectivity: 'Bluetooth 5.3, multipoint',
      Warranty: '1 year manufacturer warranty',
    },
  },
  {
    id: 'a-1',
    name: 'Over-Ear Studio Headphones',
    description:
      'Reference-grade 40mm drivers, plush memory-foam earcups, and 60 hours of wireless playback for critical listening sessions.',
    price: 8999,
    mrp: 12999,
    currency: 'INR',
    category: 'Audio',
    rating: 4.6,
    inStock: true,
    imageUrl: unsplash('photo-1505740420928-5e560c06d30e'),
    highlights: [
      '40mm reference drivers with studio tuning',
      '60-hour battery, USB-C fast charge',
      'Foldable design with hard travel case',
    ],
  },
  {
    id: 'a-2',
    name: 'Portable Smart Speaker',
    description:
      'Room-filling 360° sound with a built-in voice assistant, multi-room pairing, and 12 hours of battery on a single charge.',
    price: 3499,
    mrp: 5999,
    currency: 'INR',
    category: 'Audio',
    rating: 4.3,
    inStock: true,
    imageUrl: unsplash('photo-1545454675-3531b543be5d'),
    highlights: [
      '360° sound with deep bass radiators',
      'Built-in voice assistant and multi-room pairing',
      '12-hour battery, IPX5 splash-proof',
    ],
  },

  // ── Wearables ──────────────────────────────────────────────────────────
  {
    id: 'p-6',
    name: 'Watch Active Smartwatch',
    description:
      'Your fitness coach on the wrist. Track 90+ workouts with built-in GPS, monitor sleep and heart rate around the clock, and go up to 10 days between charges — all behind a bright always-on AMOLED display.',
    price: 12999,
    mrp: 19999,
    currency: 'INR',
    category: 'Wearables',
    rating: 4.2,
    inStock: true,
    imageUrl: unsplash('photo-1523275335684-37898b6baf30'),
    images: [
      unsplash('photo-1523275335684-37898b6baf30', 1200),
      unsplash('photo-1544117519-31a4b719223d', 1200),
      unsplash('photo-1508685096489-7aacd43bd3b1', 1200),
      unsplash('photo-1434493789847-2f02dc6ca35d', 1200),
    ],
    highlights: [
      '90+ workout modes with built-in GPS',
      '24/7 heart rate and advanced sleep tracking',
      'Always-on AMOLED display',
      'Up to 10-day battery life',
      '5ATM water resistance for swimming',
    ],
    specs: {
      Display: '1.4" AMOLED, always-on',
      Sensors: 'HR, SpO2, accelerometer, gyroscope, GPS',
      Battery: 'Up to 10 days typical use',
      'Water resistance': '5ATM',
      Compatibility: 'Android 8.0+ / iOS 12+',
      Strap: '20mm quick-release, fluoroelastomer',
      Warranty: '1 year manufacturer warranty',
    },
  },
  {
    id: 'w-1',
    name: 'Sports GPS Watch',
    description:
      'Built for runners: dual-band GPS, on-wrist pace guidance, and a rugged case that shrugs off trails and pool laps alike.',
    price: 8499,
    mrp: 11999,
    currency: 'INR',
    category: 'Wearables',
    rating: 4.3,
    inStock: true,
    imageUrl: unsplash('photo-1508685096489-7aacd43bd3b1'),
    highlights: [
      'Dual-band GPS with on-wrist pace guidance',
      'Rugged 5ATM case for trail and pool',
      '14-day battery in watch mode',
    ],
  },
  {
    id: 'w-2',
    name: 'Classic Analog Wristwatch',
    description:
      'A timeless three-hand dial on a genuine leather strap — quartz precision dressed for the boardroom and the weekend.',
    price: 5999,
    mrp: 8999,
    currency: 'INR',
    category: 'Wearables',
    rating: 4.4,
    inStock: true,
    imageUrl: unsplash('photo-1524592094714-0f0654e20314'),
    highlights: [
      'Japanese quartz movement',
      'Genuine leather strap, stainless case',
      '5ATM water resistance',
    ],
  },

  // ── Electronics ────────────────────────────────────────────────────────
  {
    id: 'e-1',
    name: 'UltraBook Pro 14',
    description:
      'A featherweight 14" powerhouse: 2.8K OLED display, 16GB RAM, and all-day battery in a 1.2kg aluminium chassis.',
    price: 89999,
    mrp: 109999,
    currency: 'INR',
    category: 'Electronics',
    rating: 4.6,
    inStock: true,
    imageUrl: unsplash('photo-1496181133206-80ce9b88a853'),
    images: [
      unsplash('photo-1496181133206-80ce9b88a853', 1200),
      unsplash('photo-1498049794561-7780e7231661', 1200),
    ],
    highlights: [
      '14" 2.8K OLED, 90Hz, 100% DCI-P3',
      '16GB RAM | 512GB NVMe SSD',
      '1.2kg aluminium body, 18-hour battery',
    ],
    specs: {
      Display: '14" 2.8K OLED, 90Hz',
      Memory: '16GB LPDDR5 | 512GB NVMe SSD',
      Weight: '1.2kg',
      Battery: 'Up to 18 hours',
      Ports: '2× Thunderbolt 4, HDMI 2.1, 3.5mm',
      Warranty: '1 year manufacturer warranty',
    },
  },
  {
    id: 'e-2',
    name: 'Mechanical Gaming Keyboard',
    description:
      'Hot-swappable switches, per-key RGB, and a gasket-mounted deck for a typing feel that keeps up with your APM.',
    price: 6499,
    mrp: 9999,
    currency: 'INR',
    category: 'Electronics',
    rating: 4.4,
    inStock: true,
    imageUrl: unsplash('photo-1587829741301-dc798b83add3'),
    highlights: [
      'Hot-swappable linear switches',
      'Per-key RGB with onboard profiles',
      'Gasket mount + PBT double-shot keycaps',
    ],
  },
  {
    id: 'e-3',
    name: '27" 4K UHD Monitor',
    description:
      'Factory-calibrated colour on a 27" IPS panel with USB-C 90W passthrough — one cable for laptop, power, and pixels.',
    price: 27999,
    mrp: 34999,
    currency: 'INR',
    category: 'Electronics',
    rating: 4.5,
    inStock: true,
    imageUrl: unsplash('photo-1527443224154-c4a3942d3acf'),
    highlights: [
      '4K IPS, 99% sRGB factory calibration',
      'USB-C with 90W power delivery',
      'Height/tilt/pivot ergonomic stand',
    ],
  },
  {
    id: 'e-4',
    name: 'Wireless Ergonomic Mouse',
    description:
      'Sculpted for all-day comfort with silent clicks, an 8K DPI sensor, and three-device Bluetooth switching.',
    price: 1999,
    mrp: 2999,
    currency: 'INR',
    category: 'Electronics',
    rating: 4.3,
    inStock: true,
    imageUrl: unsplash('photo-1527864550417-7fd91fc51a46'),
    highlights: [
      '8K DPI sensor with silent clicks',
      'Pairs with 3 devices over Bluetooth',
      '6-month battery on one charge',
    ],
  },
  {
    id: 'e-5',
    name: 'DSLR Camera 24MP Kit',
    description:
      'A 24MP APS-C sensor, 4K video, and the 18-55mm kit lens — everything you need to move past phone photography.',
    price: 52999,
    mrp: 61999,
    currency: 'INR',
    category: 'Electronics',
    rating: 4.7,
    inStock: true,
    imageUrl: unsplash('photo-1516035069371-29a1b244cc32'),
    highlights: [
      '24MP APS-C sensor with dual-pixel AF',
      '4K30 video with mic input',
      'Includes 18-55mm stabilised kit lens',
    ],
  },
  {
    id: 'e-6',
    name: '4K Camera Drone',
    description:
      'Cinematic 4K60 footage from a sub-250g foldable drone with 34 minutes of flight time and level-5 wind resistance.',
    price: 74999,
    mrp: 89999,
    currency: 'INR',
    category: 'Electronics',
    rating: 4.5,
    inStock: false,
    imageUrl: unsplash('photo-1473968512647-3e447244af8f'),
    highlights: [
      '4K60 HDR on a 3-axis gimbal',
      'Sub-250g — no registration needed',
      '34-minute flight time per battery',
    ],
  },
  {
    id: 'e-7',
    name: 'ProTab 11" Tablet',
    description:
      'A 120Hz 11" display, quad speakers, and stylus support make this the tablet for notes by day and movies by night.',
    price: 42999,
    mrp: 49999,
    currency: 'INR',
    category: 'Electronics',
    rating: 4.4,
    inStock: true,
    imageUrl: unsplash('photo-1544244015-0df4b3ffc6b0'),
    highlights: [
      '11" 120Hz display with slim bezels',
      'Quad speakers tuned for Dolby Atmos',
      'Low-latency stylus support',
    ],
  },

  // ── Fashion ────────────────────────────────────────────────────────────
  {
    id: 'f-1',
    name: 'Classic Denim Jacket',
    description:
      'Stone-washed heavyweight denim with a sherpa-lined collar — the layer that works over everything you own.',
    price: 2499,
    mrp: 3999,
    currency: 'INR',
    category: 'Fashion',
    rating: 4.4,
    inStock: true,
    imageUrl: unsplash('photo-1551028719-00167b16eac5'),
    highlights: [
      'Heavyweight 12oz stone-washed denim',
      'Sherpa-lined collar',
      'Unisex fit, sizes XS–XXL',
    ],
  },
  {
    id: 'f-2',
    name: 'Runner Sneakers',
    description:
      'Responsive foam midsole, breathable knit upper, and a grippy outsole rated for 800km of road miles.',
    price: 4299,
    mrp: 6999,
    currency: 'INR',
    category: 'Fashion',
    rating: 4.5,
    inStock: true,
    imageUrl: unsplash('photo-1542291026-7eec264c27ff'),
    highlights: [
      'Responsive EVA foam midsole',
      'Breathable engineered-knit upper',
      'Outsole rated for 800km',
    ],
  },
  {
    id: 'f-3',
    name: 'Urban Leather Backpack',
    description:
      'Full-grain leather, a padded 15.6" laptop sleeve, and quick-access pockets for a commute in style.',
    price: 3499,
    mrp: 4999,
    currency: 'INR',
    category: 'Fashion',
    rating: 4.6,
    inStock: true,
    imageUrl: unsplash('photo-1553062407-98eeb64c6a62'),
    highlights: [
      'Full-grain leather with brass hardware',
      'Padded 15.6" laptop sleeve',
      'Water-resistant lining',
    ],
  },
  {
    id: 'f-4',
    name: 'Aviator Sunglasses',
    description:
      'Polarised UV400 lenses in a featherweight metal frame — the silhouette that never goes out of season.',
    price: 1799,
    mrp: 2999,
    currency: 'INR',
    category: 'Fashion',
    rating: 4.2,
    inStock: true,
    imageUrl: unsplash('photo-1572635196237-14b3f281503f'),
    highlights: ['Polarised UV400 lenses', 'Featherweight alloy frame', 'Includes hard case'],
  },
  {
    id: 'f-5',
    name: 'Essential Cotton Tee (2-pack)',
    description:
      '100% combed organic cotton in a pre-shrunk regular fit. One in white, one in black — wardrobe solved.',
    price: 999,
    mrp: 1499,
    currency: 'INR',
    category: 'Fashion',
    rating: 4.3,
    inStock: true,
    imageUrl: unsplash('photo-1521572163474-6864f9cf17ab'),
    highlights: ['100% combed organic cotton', 'Pre-shrunk regular fit', 'White + black 2-pack'],
  },

  // ── Home & Kitchen ─────────────────────────────────────────────────────
  {
    id: 'h-1',
    name: 'Ceramic Dinner Set (16 pc)',
    description:
      'Hand-glazed stoneware for four: dinner plates, side plates, bowls, and mugs that are dishwasher and microwave safe.',
    price: 3999,
    mrp: 5999,
    currency: 'INR',
    category: 'Home & Kitchen',
    rating: 4.5,
    inStock: true,
    imageUrl: unsplash('photo-1556911220-bff31c812dba'),
    highlights: [
      'Hand-glazed stoneware, service for 4',
      'Dishwasher and microwave safe',
      'Chip-resistant rolled edges',
    ],
  },
  {
    id: 'h-2',
    name: 'Espresso Coffee Maker',
    description:
      '15-bar pressure, a steam wand for silky microfoam, and a thermoblock that heats up in 30 seconds flat.',
    price: 15999,
    mrp: 21999,
    currency: 'INR',
    category: 'Home & Kitchen',
    rating: 4.6,
    inStock: true,
    imageUrl: unsplash('photo-1495474472287-4d71bcdd2085'),
    highlights: [
      '15-bar Italian pump',
      'Steam wand for latte art microfoam',
      '30-second thermoblock heat-up',
    ],
  },
  {
    id: 'h-3',
    name: 'Accent Armchair',
    description:
      'Mid-century lines in soft bouclé upholstery with solid-oak legs — a reading corner waiting to happen.',
    price: 18999,
    mrp: 25999,
    currency: 'INR',
    category: 'Home & Kitchen',
    rating: 4.4,
    inStock: true,
    imageUrl: unsplash('photo-1586023492125-27b2c045efd7'),
    highlights: [
      'Soft bouclé upholstery',
      'Solid oak legs, 150kg rated',
      'Assembles in under 10 minutes',
    ],
  },
  {
    id: 'h-4',
    name: "Chef's Knife Set (5 pc)",
    description:
      'High-carbon stainless blades, full-tang handles, and a magnetic walnut block — sharp out of the box, easy to keep that way.',
    price: 2999,
    mrp: 4499,
    currency: 'INR',
    category: 'Home & Kitchen',
    rating: 4.3,
    inStock: true,
    imageUrl: unsplash('photo-1466637574441-749b8f19452f'),
    highlights: [
      'High-carbon stainless steel blades',
      'Full-tang riveted handles',
      'Magnetic walnut storage block',
    ],
  },

  // ── Beauty ─────────────────────────────────────────────────────────────
  {
    id: 'b-1',
    name: 'Skincare Essentials Kit',
    description:
      'A dermatologist-approved four-step routine: gentle cleanser, vitamin C serum, ceramide moisturiser, and SPF 50.',
    price: 2499,
    mrp: 3499,
    currency: 'INR',
    category: 'Beauty',
    rating: 4.5,
    inStock: true,
    imageUrl: unsplash('photo-1596462502278-27bfdc403348'),
    highlights: [
      '4-step routine for all skin types',
      '10% vitamin C serum',
      'Fragrance-free and cruelty-free',
    ],
  },
  {
    id: 'b-2',
    name: 'Matte Lipstick Set (4 shades)',
    description:
      'Four transfer-proof matte shades from everyday nude to statement red, enriched with vitamin E so lips never dry out.',
    price: 1299,
    mrp: 1999,
    currency: 'INR',
    category: 'Beauty',
    rating: 4.2,
    inStock: false,
    imageUrl: unsplash('photo-1586495777744-4413f21062fa'),
    highlights: [
      'Transfer-proof 12-hour wear',
      'Vitamin E enriched formula',
      '4 curated shades, nude to red',
    ],
  },
  {
    id: 'b-3',
    name: 'Midnight Eau de Parfum 100ml',
    description:
      'Bergamot and black pepper over a warm amber base — a long-lasting evening signature with 12-hour sillage.',
    price: 3999,
    mrp: 5999,
    currency: 'INR',
    category: 'Beauty',
    rating: 4.6,
    inStock: true,
    imageUrl: unsplash('photo-1541643600914-78b084683601'),
    highlights: [
      'Bergamot, black pepper, amber accord',
      '12-hour longevity',
      '100ml eau de parfum concentration',
    ],
  },

  // ── Daily Essentials ───────────────────────────────────────────────────
  {
    id: 'p-7',
    name: 'Fresh Strawberries 500g',
    description:
      'Hand-picked at first light from hill-country farms and cold-chain delivered the same day. These strawberries are plump, deep red, and naturally sweet — perfect for snacking, desserts, or a morning smoothie.',
    price: 199,
    mrp: 299,
    currency: 'INR',
    category: 'Daily Essentials',
    rating: 4.6,
    inStock: true,
    imageUrl: unsplash('photo-1464965911861-746a04b4bca6'),
    images: [
      unsplash('photo-1464965911861-746a04b4bca6', 1200),
      unsplash('photo-1518635017498-87f514b751ba', 1200),
      unsplash('photo-1543528176-61b239494933', 1200),
      unsplash('photo-1587393855524-087f83d95bc9', 1200),
    ],
    highlights: [
      'Hand-picked the same morning they ship',
      'Cold-chain maintained from farm to doorstep',
      'No artificial ripening agents',
      'Rich in vitamin C and antioxidants',
    ],
    specs: {
      'Net weight': '500g',
      Grade: 'Premium A',
      Origin: 'Mahabaleshwar, Maharashtra',
      Storage: 'Refrigerate at 2–4°C, consume within 3 days',
      'Best for': 'Snacking, desserts, smoothies',
    },
  },
  {
    id: 'p-8',
    name: 'Alphonso Mangoes 1kg',
    description:
      'The king of mangoes, from the orchards of Ratnagiri. Naturally ripened in hay for that signature saffron flesh, honeyed aroma, and melt-in-the-mouth texture. Each box is hand-graded for size and sweetness.',
    price: 349,
    mrp: 499,
    currency: 'INR',
    category: 'Daily Essentials',
    rating: 4.8,
    inStock: false,
    imageUrl: unsplash('photo-1553279768-865429fa0078'),
    images: [
      unsplash('photo-1553279768-865429fa0078', 1200),
      unsplash('photo-1591073113125-e46713c829ed', 1200),
      unsplash('photo-1601493700631-2b16ec4b4716', 1200),
      unsplash('photo-1605027990121-cbae9e0642df', 1200),
    ],
    highlights: [
      'GI-tagged Ratnagiri Alphonso',
      'Naturally ripened in hay — no carbide',
      'Hand-graded for size and sweetness',
      'Approximately 4–6 mangoes per kilogram',
    ],
    specs: {
      'Net weight': '1kg (4–6 count)',
      Variety: 'Alphonso (Hapus)',
      Origin: 'Ratnagiri, Maharashtra',
      Ripening: 'Natural, in hay',
      Storage: 'Room temperature until ripe, then refrigerate',
    },
  },
  {
    id: 'd-1',
    name: 'Hass Avocados (4 pack)',
    description:
      'Creamy, ready-to-ripen Hass avocados — ideal for toast, guacamole, and salads. Ships firm with ripening guide.',
    price: 299,
    mrp: 399,
    currency: 'INR',
    category: 'Daily Essentials',
    rating: 4.4,
    inStock: true,
    imageUrl: unsplash('photo-1523049673857-eb18f1d7b578'),
    highlights: ['Premium Hass variety', 'Ships firm with ripening guide', 'Rich in healthy fats'],
  },
  {
    id: 'd-2',
    name: 'Organic Bananas (1 dozen)',
    description:
      'Naturally ripened, certified-organic bananas from Western Ghats farms — the everyday energy snack.',
    price: 79,
    mrp: 99,
    currency: 'INR',
    category: 'Daily Essentials',
    rating: 4.5,
    inStock: true,
    imageUrl: unsplash('photo-1571771894821-ce9b6c11b08e'),
    highlights: ['Certified organic', 'Naturally ripened', 'High in potassium and fibre'],
  },
  {
    id: 'd-3',
    name: 'Nagpur Oranges 1kg',
    description:
      'Juicy, thin-skinned Nagpur oranges bursting with vitamin C — squeeze them, segment them, or just peel and go.',
    price: 129,
    mrp: 179,
    currency: 'INR',
    category: 'Daily Essentials',
    rating: 4.3,
    inStock: true,
    imageUrl: unsplash('photo-1547514701-42782101795e'),
    highlights: ['Thin-skinned Nagpur variety', 'High juice yield', 'Rich in vitamin C'],
  },
  {
    id: 'd-4',
    name: 'Sourdough Bread Loaf',
    description:
      'Naturally leavened 48-hour sourdough with a crackling crust and open crumb, baked fresh every morning.',
    price: 149,
    mrp: 199,
    currency: 'INR',
    category: 'Daily Essentials',
    rating: 4.6,
    inStock: true,
    imageUrl: unsplash('photo-1509440159596-0249088772ff'),
    highlights: ['48-hour natural fermentation', 'Baked fresh daily', 'No commercial yeast'],
  },
  {
    id: 'd-5',
    name: 'Farm Fresh Milk 1L',
    description:
      'Single-origin A2 cow milk, pasteurised and bottled within hours of milking. Delivered chilled in returnable glass.',
    price: 65,
    mrp: 75,
    currency: 'INR',
    category: 'Daily Essentials',
    rating: 4.7,
    inStock: true,
    imageUrl: unsplash('photo-1550583724-b2692b85b150'),
    highlights: ['A2 single-origin milk', 'Bottled within hours of milking', 'Returnable glass bottle'],
  },
];
